### ISSUE TITLE
Замечания по Lab 0 Task 4

### ISSUE THREAD

**Issue by alexey-malov** [sadovin-viktor/ps-oop#2]
- [x] Цикл вычисления выражения вынести в функцию

- [x] switch-case для вычисления результата операции также вынести в функцию

**Comment by alexey-malov** [comment]
- [ ] Не использовать Exit

**Comment by alexey-malov** [comment]
```c++
		else //Ожидаем операцию
		{
			operation = argv[i];
			if (operation.size() > 1)
				Error("Error, in operation. This operation: \"" + operation + "\" is not exist.");
		}
```

- [ ] Строка может быть пустой и проверка её пропустит

**Comment by alexey-malov** [comment]
```c++
	cout << "Total: " << total << endl;
	cin.get();
	return 0;
```

- [ ] Программе не должна ожидать какого-либо ввода от пользователя

**Comment by alexey-malov** [comment]
```
1>c:\teaching\2018\oop\sadovin\ps-oop\lab0\lab0\labs\addtask4\main.cpp(83): warning C4101: 'err': unreferenced local variable
1>c:\teaching\2018\oop\sadovin\ps-oop\lab0\lab0\labs\addtask4\main.cpp(87): warning C4101: 'err': unreferenced local variable
```
- [ ] Программа должна компилироваться без предупреждений компилятора во всех конфигурациях и платформах.

**Comment by sadovin-viktor** [comment]
Исправлено

**Comment by alexey-malov** [comment]
```c++
bool CheckOperation(string &currOperation)
```

- [ ] Ссылка должна быть константная

**Comment by alexey-malov** [comment]
```c++
bool CalculateOperands(string &operation, double &total, const double currValue)
{
	switch (operation[0])
	{
	case '+':
		total += currValue;
		break;
	case '-':
		total -= currValue;
		break;
	case '*':
		total *= currValue;
		break;
	case '/':
		if (currValue == 0)
		{
			cout << "Error, division by 0 is impossible." << endl;
			return false;
		}
		total /= currValue;
		break;
	}

	return true;
}
```

- [ ] Назвать ApplyOperation
- [ ] строку принимать по константной ссылке

**Comment by alexey-malov** [comment]
- [ ] Переменные лучше объявлять ближе к их месту первого использования

**Comment by alexey-malov** [comment]
```c++
bool CheckOperation(const string &currOperation)
{
	if (currOperation.size() != 1)
		return false;

	string alphabet = "+-/*";

	int i;
	for (i = 0; i < 4; i++)
		if (currOperation[0] == alphabet[i])
			break;

	if (i == 4)
		return false;

	return true;
}
```

- [ ] Перебор организовать через range-based for

**Comment by alexey-malov** [comment]
```c++
	bool isOk;
	isOk = CalculateExpression(argc, argv, answer);
	if (!isOk)
		return 1;

```

- [ ] isOk не нужна

**Comment by AniSkyWorker** [comment]
Советы:
- в нашем code convetion при использовании операторов условий и циклов содержимое должно быть в фигурных скобках
- в функцию ```CalculateExpression``` нежелательно передавать переменную answer, которая при передаче ничего полезного в себе не содержит, проще возвращать ответ из функции, а ошибки обрабатывать либо в еще одной функции, либо в main, через try-catch
- неизменные переменные вроде alphabet в CheckOperation можно вынести как константу в глобальную область видимости
```
const string alphabet = "+-/*"; // в области видимости функции
constexpr char alphabet[] = "+-/*"; // в глобальной области видимости, позволит определить переменную на этапе компиляции
```
k = 1.0
