### ISSUE TITLE
Замечания по программе Replace

### ISSUE THREAD

**Issue by oMystique** [sadovin-viktor/ps-oop#4]
- [ ] Имеются предупреждения компилятора при компиляции программы
![default](https://user-images.githubusercontent.com/14878773/37063734-754cee20-21ab-11e8-973a-454693f9f911.png)

- [ ] Пустоту строки можно проверять методом `std::string::empty()`
```c++
(searchStr.size() == 0)
```

- [ ] Не совсем понятно зачем в данном случае нужна константность
```c++
	const string searchStr = argv[3];
	const string replaceStr = argv[4];
```

- [ ] Методы `.find` и `.size` возвращают `size_t`, который может не совпадать по размеру с int. Следует использовать именно `size_t`. Отсюда предупреждения компилятора. 
P.S. лучше использовать 4 уровень предупреждений.
```c++
		int startNumber = 0;
		int positionSubStr = 0;
```

- [ ] Лучше подобрать для функции другое название. Сейчас имя не отображает сути - не понятно что за таск мы запускаем, для чего он нужен и какое полезное действие в себе несет
```c++
void ExecuteTask(ifstream &in, ofstream &out, const string &searchStr, const string &replaceStr)
```

**Comment by alexey-malov** [comment]
- [ ] Выделить из main функцию, выполняющую копирование с заменой, которая принимала имена файлов и вызывал существующую функцию

**Comment by alexey-malov** [comment]
- [ ] Из ReplaceSubStrInStream выделить функцию, выполняющую замену всех вхождений строки в строке

**Comment by alexey-malov** [comment]
- [ ] Код замены подстроки в строке имеет сложность O(N^2). Сделайте файл, содержащий строку из 10 миллиона символов A и заменить в нём строку A на BB. Программа должна отработать в Release-конфигурации быстрее чем за секунду

**Comment by alexey-malov** [comment]
- [ ] Убрать функцию CopyFile. Просто функция замены должна возвращать исходную строку, если искомая пустая

**Comment by alexey-malov** [comment]
@AniSkyWorker, is_open() проверяет файл на открытость. Приведение к типу bool возвращает  для открытых файлов true (если не было ошибок), а для закрытых  - false. Поэтому обе проверки равнозначны


```ifstream in(fileName);
if (!in)
{
}
```

**Comment by alexey-malov** [comment]
```c++
string SwapSubStr(const string &currStr, const string &searchStr, const string &replaceStr)
```

- [ ] Неудачное имя функции. Переименовать
