### ISSUE TITLE
Замечания по программе invert

### ISSUE THREAD

**Issue by oMystique** [sadovin-viktor/ps-oop#5]
- [ ] Зачем переменную `isOk` объявлять заранее, а инициализировать позднее?
```c++
	bool isOk;
	
	vector<vector<double>> matrix(M_SIZE, vector<double>(M_SIZE));
	isOk = FillMatrix(in, matrix);
```

- [ ] Есть блистательно объявленная константа M_SIZE. От магических чисел следует избавиться
```c++
	for (int i = 0; i < 3; i++) //Деление каждого элемента на определитель исходной матрицы
		for (int j = 0; j < 3; j++)
			matrix[i][j] /= matrDeterm;
```

- [ ] Лучше назвать константу `MATRIX_SIZE`. Так понятнее.

- [ ] Можно вынести в отдельную функцию
```c++
	for (int row = 0; row < M_SIZE; row++) //Из матрицы миноров делаем матрицу алгебраичских дополнений
		for (int col = 0; col < M_SIZE; col++)
			if (((row + col) % 2) != 0)
				algebrCompl[row][col] *= -1;
```

- [ ] Зачем 3 переноса строки? Можно и 1.
```c++
double Determinant2x2(vector<vector<double>> &currMatr)
{
	return 
		currMatr[0][0] * currMatr[1][1] - 
		currMatr[0][1] * currMatr[1][0];
}
             !1!
             !2!
             !3!
bool FillMatrix(ifstream &in, vector<vector<double>> &matrix)
```

- [ ] Здесь так же
```c++
void GetInverseMatrix(vector<vector<double>> &matrix, const double matrDeterm)
{
	for (int i = 0; i < M_SIZE; i++) //Транспонирование матрицы алгебраичских дополнений
		for (int j = 0; j < i; j++)
			swap(matrix[i][j], matrix[j][i]);

	for (int i = 0; i < 3; i++) //Деление каждого элемента на определитель исходной матрицы
		for (int j = 0; j < 3; j++)
			matrix[i][j] /= matrDeterm;
}
             !1!
             !2!
             !3!
bool GetInverseMatrix(const vector<vector<double>> &matrix, vector<vector<double>> &inverseMatrix)
```

**Comment by alexey-malov** [comment]
- [ ] Векторы лучше не использовать из-за оверхеда. Для маленьких матрицы достаточно использовать std::array либо положить массив в структуру (чтобы можно было возвращать из функции или передавать в неё по значению).
- [ ] Завести псевдоним для типа матрицы, чтобы не ипсать каждый раз массив массивов.

**Comment by alexey-malov** [comment]
- [ ] Из main выделить функции:

- Считать матрицу из файла по его имени
- TryInvertMatrix
- PrintMatrix

**Comment by AniSkyWorker** [comment]
- [ ] по codeconvention оборачиваем все операторы условий и циклов в фигурные скобки
- [ ] ```ifstream``` следует проверять на is_open, конструирования с именем файла недостаточно
- [ ] по умолчанию матрица алгебраических дополнений должна быть заполнена нулями, в нее передается ```inverseMatrix```, которая будет проинициализирована дефолтными значениями double (как повезет), стоит инициализировать ее нулями явно.
- [ ] из ```TranosformInToMinorMatrix``` можно сразу возвращать матрицу дополнений, а не передавать изначальную по ссылке
k = 0.7

**Comment by alexey-malov** [comment]
```c++
	if (!FillMatrix(argv[1], mainMatrix))
	{
		return 1;
	}
```

- [ ] Имя ReadMatrix больше подходит для функции, выполняющей чтение матрицы из файла

**Comment by alexey-malov** [comment]
```c++
void InitializeByZero(Matrix3x3 &matrix)
{
	for (int row = 0; row < matrix.size(); row++)
	{
		for (int col = 0; col < matrix[row].size(); col++)
		{
			matrix[row][col] = 0;
		}
	}
}
```
Незачем городить циклы и функцию, где `matrix = {};` справляется

**Comment by alexey-malov** [comment]
```c++
void TransformInverseMatrix(Matrix3x3 &matrix, double matrDeterm)
{
	for (int i = 0; i < MATRIX_SIZE; i++) //Транспонирование матрицы алгебраичских дополнений
	{
		for (int j = 0; j < i; j++)
		{
			swap(matrix[i][j], matrix[j][i]);
		}
	}

	for (int i = 0; i < MATRIX_SIZE; i++) //Деление каждого элемента на определитель исходной матрицы
	{
		for (int j = 0; j < MATRIX_SIZE; j++)
		{
			matrix[i][j] /= matrDeterm;
		}
	}
}
```

- [ ] Цикл транспонирования матрицы выделить в отдельную функцию

**Comment by alexey-malov** [comment]
```c++
TransoformMinorToAlgebriacComplimentMatrix
```

- [ ] Исправить опечатку

**Comment by alexey-malov** [comment]
- [ ] Из функции GetMinorMatrix() выделить два самых внутренних цикла в отдельную функцию
