### ISSUE TITLE
Замечания по dec2bin

### ISSUE THREAD

**Issue by alexey-malov** [sadovin-viktor/ps-oop#6]
```c++
int StrToInt(const string &strNumber, bool &state) 
{
```

- [x] state - неудачное имя для булевой переменной

**Comment by alexey-malov** [comment]
```c++
void PrintInBinStyle(ostream &out, int number)
{
	while (number)
	{
		out << (number & 1);
		number >>= 1;
	}
}
```

- [ ] Операции битовых сдвигов для знаковых целых чисел ведут себя по-разному (в т.ч. могут вызывать UB (undefined behavior). ИСпользуйте для вывода беззнаковый тип

**Comment by alexey-malov** [comment]
```c++
int StrToInt(const string &strNumber, bool &state) 
{
	try 
	{
		int number = stoi(strNumber);

		if (number < 0)
			throw runtime_error("Error, number can't be negative.");
		
		return number;
	}
	catch (out_of_range &)
	{
		cout << "Error, overflow, number to big for int-value." << endl;
		state = false;
		return -1;
	}
	catch (invalid_argument &)
	{
		cout << "Error, invalid argument. Argument must be a number!" << endl;
		state = false;
		return -1;
	}
	catch (runtime_error &err)
	{
		cout << err.what() << endl;
		state = false;
		return -1;
	}
}
```

- [ ] Почему StringToInt проверяет знак числа. Это не в её компетенции решать, может ли быть число отрицательным. Этими сведениями обладает код, её вызывающий

**Comment by AniSkyWorker** [comment]
-[] code convention(см. замечания по другим лабам)
-[] функция ```PrintInBinStyle```одновременно и выводит число и переводит его в 2ичную систему счисления

**Comment by alexey-malov** [comment]
```c++
		answer.append(to_string(number & 1));
```
- [ ] number & 1 вовращает 0 или 1. Коды символов '0' и '1' различаются на 1. У string есть append, принимающий символ, а не строку. Сделать проще
